import type { NextPage } from "next";
import Head from "next/head";
import Footer from "~/components/Footer";
import Header from "~/components/header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <h1 className="text-red-500">Main Content Area</h1>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
